apiVersion: batch/v1
kind: CronJob
metadata:
  name: export-feedback-job
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prisoner-content-hub-feedback-exporter
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
            args:
            - npm
            - start
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
          activeDeadlineSeconds: 240
